### ISSUE TITLE
Canary: fails when no ssh key has been defined

### ISSUE THREAD

**Issue by Trophime** [MSO4SC/MSOPortal#128]
Using the latest canary fails with previous settings:

```
2018-06-27T16:30:44.667Z Task started 'hpc_plugin.tasks.prepare_hpc' primary_hpc_wm3rz9 (primary_hpc)
2018-06-27T16:30:46.578Z Task failed 'hpc_plugin.tasks.prepare_hpc' -> not a valid RSA private key file primary_hpc_wm3rz9 (primary_hpc)
SSHException: not a valid RSA private key file
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/test-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 76, in prepare_hpc
    client = SshClient(config['credentials'])
  File "/opt/mgmtworker/env/plugins/default_tenant/test-hpc/lib/python2.7/site-packages/hpc_plugin/ssh.py", line 68, in __init__
    password=private_key_password)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/paramiko/pkey.py", line 205, in from_private_key
    key = cls(file_obj=file_obj, password=password)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/paramiko/rsakey.py", line 52, in __init__
    self._from_private_key(file_obj, password)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/paramiko/rsakey.py", line 178, in _from_private_key
    data = self._read_private_key('RSA', file_obj, password)
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/paramiko/pkey.py", line 265, in _read_private_key
    raise SSHException('not a valid ' + tag + ' private key file')
SSHException: not a valid RSA private key file
```

guess this is due to a missing SSH key.
could this be made optional?

**Comment by Trophime** [comment]
My bad. It works... but the button turn red at "RUN" even if the job is marked as COMPLETED...

![button_keeps_red](https://user-images.githubusercontent.com/1309311/41988433-622706b6-7a3c-11e8-975a-0d9c7d8092e9.png)

**Comment by Trophime** [comment]
the trouble is that this blueprint get stuck in the cli...
I will try with an other one then..

**Comment by Trophime** [comment]
What is actually done after the job has been completed?
