### ISSUE TITLE
external HPC ressources support broken

### ISSUE THREAD

**Issue by prudhomm** [MSO4SC/MSOPortal#75]
I tried to add atlas.math.unistra.fr but at deploy stage I get:

```
2018-05-29T23:11:51.154Z Starting node main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:51.832Z Sending task 'hpc_plugin.tasks.prepare_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:52.029Z Task started 'hpc_plugin.tasks.prepare_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:55.000Z Task succeeded 'hpc_plugin.tasks.prepare_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:55.348Z Sending task 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:55.382Z Task started 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:56.724Z Task succeeded 'hpc_plugin.tasks.start_monitoring_hpc' main_hpc_4t94bj (main_hpc)
2018-05-29T23:11:57.787Z Creating node job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:11:59.549Z Sending task 'hpc_plugin.tasks.preconfigure_job'
2018-05-29T23:11:59.641Z Task started 'hpc_plugin.tasks.preconfigure_job'
2018-05-29T23:12:01.707Z Task succeeded 'hpc_plugin.tasks.preconfigure_job'
2018-05-29T23:12:01.781Z Configuring node job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:03.082Z Starting node job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:03.241Z Sending task 'hpc_plugin.tasks.bootstrap_job' job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:03.366Z Task started 'hpc_plugin.tasks.bootstrap_job' job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:06.175Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

2018-05-29T23:12:21.327Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 1/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:21.413Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 1/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:24.012Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment [retry 1/5] job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

2018-05-29T23:12:39.175Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 2/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:39.476Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 2/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:42.778Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment [retry 2/5] job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

2018-05-29T23:12:57.939Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 3/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:12:58.056Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 3/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:13:01.163Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment [retry 3/5] job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

2018-05-29T23:13:16.329Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 4/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:13:16.463Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 4/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:13:19.468Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment [retry 4/5] job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

2018-05-29T23:13:34.614Z Sending task 'hpc_plugin.tasks.bootstrap_job' [retry 5/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:13:34.809Z Task started 'hpc_plugin.tasks.bootstrap_job' [retry 5/5] job_toolboxes_61eioz (job_toolboxes)
2018-05-29T23:13:37.902Z Task failed 'hpc_plugin.tasks.bootstrap_job' -> local variable 'exit_code' referenced before assignment [retry 5/5] job_toolboxes_61eioz (job_toolboxes)
UnboundLocalError: local variable 'exit_code' referenced before assignment
	Traceback (most recent call last):
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 641, in main
    payload = handler.handle()
  File "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/dispatch.py", line 397, in handle
    result = self.func(*self.args, **kwargs)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 248, in bootstrap_job
    skip_cleanup)
  File "/opt/mgmtworker/env/plugins/default_tenant/csm-cp1-hpc/lib/python2.7/site-packages/hpc_plugin/tasks.py", line 343, in deploy_job
    return exit_code is 0
UnboundLocalError: local variable 'exit_code' referenced before assignment

```

**Comment by victorsndvg** [comment]
@prudhomm , @gdolle I think it's connecting to the HPC, the issue seems to be in the bootstrap process/script. I'm right?

**Comment by gdolle** [comment]
No I don't think so. But maybe it's how we configure. I think I added a LUSTRE variable in the user bashrc. That must be the problem I guess..

**Comment by victorsndvg** [comment]
And this variable has sense in Atlas?

**Comment by gdolle** [comment]
No. But to avoid the user to configure the paths in instances when they switch from cesga to atlas, I added his variable. If we had profiles per machine, that would be easier.

**Comment by victorsndvg** [comment]
Then maybe this is not the right title for the issue. Do you agree? can you write something more descriptive?

**Comment by prudhomm** [comment]
@victorsndvg @emepetres any idea when will this issue be fixed. So that our end users can use mso4sc?

**Comment by gdolle** [comment]
I think it's because there's an entry in the experiment input with ($LUSTRE) to indicate where to put the data. (See the example one https://github.com/MSO4SC/resources/blob/master/blueprint-examples/single-singularity-job/blueprint.yaml#L85)
When the orchestrator send an ssh command to create the slurm script and then run the script. It expects to use Lustre system and have a LUSTRE variable.
I put this variable in the bashrc of the orchestrator user on atlas, but I think this variable isn't read or too late.

**Comment by emepetres** [comment]
For now, why don't you just put the path as an input? So in cesga it would be something involving $LUSTRE, and in Atlas other value. (For example, put the workdir as an input)
